### ISSUE TITLE
Error: Cannot find module 'eslint-config-rgui/loose'

### ISSUE THREAD

**Issue by showzyl** [rainfore/pursuit-cli#12]
/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config/config-file.js:408
            throw e;
            ^

Error: Cannot find module 'eslint-config-rgui/loose'
Referenced from: /Users/showzyl/Desktop/demo/.eslintrc.js
    at ModuleResolver.resolve (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config/config-file.js:485:25)
    at load (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config/config-file.js:502:26)
    at configExtends.reduceRight (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config/config-file.js:536:22)
    at loadConfig (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/eslint/lib/cli-engine.js:754:26)
    at verify (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/gulp-eslint/index.js:20:25)
    at Transform.util.transform [as _transform] (/Users/showzyl/.nvm/versions/node/v7.6.0/lib/node_modules/pursuit-cli/node_modules/gulp-eslint/index.js:70:17)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)

**Comment by z-ZYS-s** [comment]
Thanks，请升级一下版本。pursuit也重新clone一下。
